#!/usr/bin/env bash
# get the current directory of the script
SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd)
echo $1
nohup gnome-terminal --geometry=200x50 --working-directory="$SCRIPT_DIR" -- "$SCRIPT_DIR/dive" "$1" > /dev/null 2>&1 &
exit 0
